### ISSUE TITLE
Import Encyclopedia data in Firebase

### ISSUE THREAD

**Issue by jacobalpowers** [SCCapstone/BoredBards#137]
Need to research and import data from outside sources into database for use in the Encyclopedia page.

```[tasklist]
### Tasks
- [x] Research Database to be imported
- [x] Find way to convert database from whatever format given to JSON objects
- [x] Import data into Firebase
```
