### ISSUE TITLE
Tasks for Weeks of Oct. 31, 2022 - Nov. 18, 2022

### ISSUE THREAD

**Issue by csimons637** [SCCapstone/BoredBards#55]
What are we completing for the week of November 7:
- [x] Campaigns class #53 
- [ ] UI for Notes and Home Screens (XML) #50 
- [ ] Database
- [x] Finish player classes #36
- [x] Change color palette(s) #56
- [ ] Random name generator #48
